-- Migration 022: record whether the CURRENTLY PENDING handoff token was minted
-- by `session_handoff { force_reissue: true }` (issue #298).
--
-- # What this closes
--
-- `force_reissue` re-leases a session whose generation holder died. It is
-- gated on the session being demonstrably dead — but minting a token stamps
-- `pending_handoff_issued_at`, one of the five signals that gate reads, so a
-- successful forced reissue makes its own session read live and the caller's
-- own retry would be refused for liveness the caller itself created (D-P1).
--
-- The remedy was to exclude that one column from the staleness read when a
-- token is already pending. That works, but the exclusion could not tell two
-- states apart, because the only column that differs between them is the
-- excluded one:
--
--   (a) a token the FORCED path minted moments ago      -> must be admitted
--   (b) a token a LIVE incumbent minted moments ago      -> must be refused
--       through a generation-authenticated call
--
-- On a session otherwise quiet for COLLAB_DEAD_SESSION_SECS, (b) was therefore
-- admitted: a third process could wait for an incumbent's ordinary mint->claim
-- window (which `collab_status` advertises un-gated as `handoff_pending`), call
-- `force_reissue`, receive the incumbent's token verbatim, and claim it. The
-- intended successor saw only `handoff_token already claimed`.
--
-- Telling (a) from (b) needs *provenance* — which path minted the pending
-- token — and provenance has to be a durable bit written at mint time. It
-- cannot be derived: `pending_handoff_generation` is `generation + 1` on both
-- paths, the forced path deliberately leaves the active `generation` untouched
-- (the anti-resurrection property of issue #91), the advisory generation cache
-- is per-process and so cannot answer for the freshly-started process a rescue
-- is *for*, and neither path writes `collab_sessions.updated_at`.
--
-- Reading it back out of the `session_handoff.force_reissue` wal_log row was
-- considered and rejected: that inverts the usual direction by making an
-- authorization decision depend on an audit table, and `wal_prune` deletes
-- those rows on the retention window — which would silently turn a retention
-- setting into a security parameter.
--
-- # Why the default is 0, and why that is the safe answer
--
--   pending_handoff_forced   0 = this pending token was minted by an ordinary,
--                                generation-authenticated `session_handoff`
--                                call (or the row predates this migration, or
--                                nothing is pending at all)
--                            1 = minted by the forced path
--
-- 0 selects the FULL five-signal staleness predicate, which refuses on a live
-- session. 1 selects the narrowed predicate that skips this agent's own
-- `pending_handoff_issued_at`. So an unknown provenance fails CLOSED: every
-- pre-022 row, and any row written by a future path that forgets to set this,
-- is treated as a normally-minted token and gets the strict gate. The
-- permissive answer is never the default — which is the same reason
-- `force_reissue_admits_phase` is an exhaustive `match` rather than a
-- `matches!`.
--
-- NOT NULL rather than nullable-with-a-fail-safe-reader (the shape migration
-- 021 chose for `attestation_check`): here there is no third state worth
-- distinguishing. 021 needed NULL because "no verdict recorded" is genuinely
-- different from a negative finding and readers must render it differently.
-- A token is either forced-minted or it is not, and "we do not know" is
-- operationally identical to "not forced" — it takes the strict gate either
-- way — so collapsing them into one value removes a state that could only ever
-- be mishandled.
--
-- # Lifetime: provenance never outlives the token it describes
--
-- The flag describes the *pending* token, not the row and not the lease. It is
-- written on a fresh issue (set by the forced path, cleared by the normal one,
-- so a row that once carried a forced token cannot leave a stale 1 behind to be
-- inherited), left untouched on the reuse path (which writes nothing at all and
-- must not flip provenance either — a forced call that reuses a normally-minted
-- token keeps 0, and is therefore refused on a live session, which is exactly
-- the attack path staying shut), and cleared by `claim_handoff_token` alongside
-- the other pending columns.
--
-- A separate migration rather than an edit to 010, for the reason 021 gives:
-- 010 has long since shipped, its `CREATE TABLE IF NOT EXISTS` would silently
-- skip an existing database, and this code would then query a missing column.
-- The ladder is the mechanism that makes adding a column to an existing table
-- safe.

ALTER TABLE collab_actor_generations ADD COLUMN pending_handoff_forced INTEGER
    NOT NULL DEFAULT 0
    CHECK (pending_handoff_forced IN (0, 1));

INSERT OR IGNORE INTO schema_version (version) VALUES (22);
